### ISSUE TITLE
This project is supposed to be in the bundle, but it is being ignored by build process

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_ADS1x15#2]
The build-bundle.py build script ignores all  subdirectories unless there is a file `__init__.py` in the subdirectory.  I tried to build the bundle and this library did NOT get included, because it needs that special file.

**Comment by mrmcwethy** [comment]
I have a fix pushed.  Added __init__.py to subdirectory

**Comment by caternuson** [comment]
#3 merged. reopen if that doesn't fix.
