### ISSUE TITLE
Move consts related to user settings to class level.

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_ADS1x15#21]
The register addresses are OK at the module level. But for things like mode (maybe that's the only one?) there is no convenient way to access them when using the recommended code setup:
```python
import board, busio
import adafruit_ads1x15.ads1015 as ADS
from adafruit_ads1x15.analog_in import AnalogIn

i2c = busio.I2C(board.SCL, board.SDA)
ads = ADS.ADS1015(i2c)
ads.mode = 0 # don't have access to _ADS1X15_CONFIG_MODE_CONTINUOUS  
``` 
Having these at the class level would allow:
```python
ads.mode = ADS._ADS1X15_CONFIG_MODE_CONTINUOUS
```
May also want to change their names? Or just add new ones? So could:
```python
ads.mode = ADS.CONTINUOUS
```

**Comment by tannewt** [comment]
Module level is how I've seen it done in other places. The more proper way is to do it as a Python enum which is essentially an empty class with statics. So it'd be `ads.mode = ADS.Mode.CONTINUOUS`. `digitalio.Pull` is modeled this way.

**Comment by caternuson** [comment]
Thanks. That make more sense. I'll try and implement something and PR it.

**Comment by sommersoft** [comment]
Just tossing in my support/agreeance @caternuson. These could definitely be more useful at the class level, especially so that the user doesn't have to remember which integer matches a mode.

**Comment by caternuson** [comment]
Yah, I totally did a sloppy job on this. I hit this myself when I was trying to help someone change mode and realized they didn't have anything convenient to use on the right hand side. They need to be able to do `ads.mode = SOMETHING_OBVIOUS_AND_EASY_TO_REMEMBER`

**Comment by caternuson** [comment]
Done. See #25

**Comment by makermelissa** [comment]
Did you want to do the release?

**Comment by makermelissa** [comment]
Or I can... :)

**Comment by caternuson** [comment]
Thanks!
