### ISSUE TITLE
Scale value to 16 bits?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_ADS1x15#29]
Should this library scale `value` to 16 bits like the core API does?
https://circuitpython.readthedocs.io/en/latest/shared-bindings/analogio/AnalogIn.html#analogio.AnalogIn.value

**Comment by ladyada** [comment]
yep

**Comment by caternuson** [comment]
okie dokie.

**Comment by caternuson** [comment]
Fixed by #31

Thanks @dherrada
