### ISSUE TITLE
Different data rates yield the same SPS

### ISSUE THREAD

**Issue by btbernstein** [adafruit/Adafruit_CircuitPython_ADS1x15#35]
Data collection with my ADS1115 always results in approximately the same samples per second, regardless of what is specified. I have tested ads1x15_fast_read.py with each rate, no other modifications, and I always receive ~415 SPS. 

Any help with this would be appreciated.
Thank you

**Comment by caternuson** [comment]
There is currently no syncing with actual data conversion completion. Much more discussion and details here:
https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15/issues/27

The only option currently available is to do something like this: 
```python
# Read the same channel over and over
for i in range(SAMPLES):
    data[i] = chan0.value
    time.sleep(SOME_DELAY)
```

Without the `sleep`, the loop will run as fast as possible regardless of sample rate.
