### ISSUE TITLE
ADS1115 Addressing

### ISSUE THREAD

**Issue by rrsquez** [adafruit/Adafruit_CircuitPython_ADS1x15#71]
Hello, this isn't a bug, but it looks like this driver doesn't support multiple addresses. The ADS1115 has 4 addresses, so we should be able to connect 4 of them to the same I2C bus, given they each have different addresses (ADR pin to: GND, VCC, SDA or SCL). 
Could you please add this feature to the next revision of this code?

Thank you, Richard Vasquez

**Comment by caternuson** [comment]
There's an `address` parameter you can use to specify a non-default address.
```python
ads = ADS.ADS1015(i2c, address=0x49)
```
