### ISSUE TITLE
Misspelled comment

### ISSUE THREAD

**Issue by nlantau** [adafruit/Adafruit_CircuitPython_ADS1x15#76]
Misspelled word in comment 'single' as 'sinlge' on line 19

https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15/blob/e11d0414d695fc7d50e9a79c732e4901c27ceeb2/examples/ads1x15_gain_example.py#L19

**Comment by FoamyGuy** [comment]
@nlantau thank you. Are you interested in submitting a PR to change the spelling?

**Comment by caternuson** [comment]
Yep. Thanks @nlantau 

This would be a good first PR.

**Comment by nlantau** [comment]
@FoamyGuy @caternuson yes, sure thing!

**Comment by nlantau** [comment]
This issue has been resolved and merged into main. Closing it.
