### ISSUE TITLE
Code of Conduct in README is broken

### ISSUE THREAD

**Issue by scirelli-c1** [adafruit/Adafruit_CircuitPython_ADS1x15#82]
Code of Conduct in README is broken. I get a 404.
https://github.com/adafruit/Adafruit_CircuitPython_CircuitPython_ADS1x15/blob/main/CODE_OF_CONDUCT.md

**Comment by tekktrik** [comment]
Proper link is https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15/blob/main/CODE_OF_CONDUCT.md, do you wanna submit a PR fix?

**Comment by scirelli-c1** [comment]
Sure! I'll work on it tomorrow

**Comment by scirelli** [comment]
Hi @tekktrik, I just realized I created this PR but I'm not aware of any contributing guidelines for this project. The contributing section only has the Code of Conduct. Please let me know if there's anything I need to do/missed with this PR and the next one I'll pick up #83.
