### ISSUE TITLE
busio.i2c issue

### ISSUE THREAD

**Issue by chubohao** [adafruit/Adafruit_CircuitPython_ADS1x15#87]
Hello,

I am using this driver on my Computing Module 4, and I using the I2C3, but the busio.i2c prompted " ValueError: No Hardware I2C on (scl,sda)=(5, 4), Valid I2C ports: ((1, 3, 2), (0, 1, 0), (10, 45, 44))", does it mean that the i2c3 of CM4 is not supported by buiso?

Best wishes and looking forward to your reply.

Bohao

**Comment by tekktrik** [comment]
It looks like Blinka only defines those 3 ports as valid I2C ports.  If you're looking for help with specific issues relating to the CM4 and how to possibly use other ports, try using the Adafruit Support Forums or the Adafruit Discord server where you'll have better luck.  Thanks!
