### ISSUE TITLE
Any plans to implement the comparator?

### ISSUE THREAD

**Issue by rdagger** [adafruit/Adafruit_CircuitPython_ADS1x15#88]
The ability to utilize the built-in traditional or windowed comparator in either latching or non-latching mode would be very useful.

**Comment by tekktrik** [comment]
I don't think there are any plans currently, but we would love to receive a PR for it!  Is that something you'd be interested in doing?

**Comment by RoaCode** [comment]
I've added a PR to add the comparator functionality.

**Comment by FoamyGuy** [comment]
resolved by: #98
