### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [adafruit/Adafruit_CircuitPython_ADS1x15#89]
Hi, In **Adafruit_CircuitPython_ADS1x15**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
Adafruit-Blinka
adafruit-circuitpython-busdevice
typing-extensions~=4.0
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **Adafruit-Blinka** can be changed to *>=0.1.5,<=8.0.2*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the Adafruit-Blinka</summary>
 <pre>micropython.const
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>self._conversion_complete
datetime.datetime.now
adafruit_ads1x15.analog_in.AnalogIn
self._read
list
_ADS1115_CONFIG_DR.keys
_ADS1015_CONFIG_DR.keys
os.path.abspath
i2c.write
_ADS1X15_CONFIG_GAIN.keys
self._write_register
self._data_rate_default
sphinx_rtd_theme.get_html_theme_path
busio.I2C
raw_adc.to_bytes
range
sys.path.insert
format
micropython.const
print
ValueError
_ADS1X15_DIFF_CHANNELS.keys
adafruit_ads1x15.ads1115.ADS1115
self._read_register
struct.unpack
time.sleep
i2c.readinto
self.get_last_result
time.monotonic
os.environ.get
list.sort
self._ads.read
self._conversion_value
adafruit_bus_device.i2c_device.I2CDevice
adafruit_ads1x15.ads1015.ADS1015
str
NotImplementedError
i2c.write_then_readinto
bytearray
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by tekktrik** [comment]
I don't think a change like this makes sense for our project or needs.  Thanks for offering though!
